version: '3.1'
services:
  api:
    build: ./
    environment:
      - DB_PORT=5432
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=pass
      - DB_DBNAME=postgres
      - DB_SSL_MODE=disable
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: always

  postgres:
    image: "postgres:latest"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
    ports:
      - "54320:5432"
    volumes:
      - /data/db/postgres:/var/lib/postgresql/data